name: Approve And Merge Dependabot PR Trigger

on:
  pull_request:

jobs:
  gradle-check:
    name: Approve And Merge Dependabot PR Trigger
    uses: interlok-tooling/reusable-workflows/.github/workflows/approve-merge-dependabot-pr-trigger.yml@main
    secrets:
      DEPENDABOT_APPROVE_MERGE_GITHUB_TOKEN: ${{ secrets.DEPENDABOT_APPROVE_MERGE_GITHUB_TOKEN }}
