name: Publish 3.12 Release

on:
  workflow_dispatch:
    inputs:
      interlok-version:
        description: 'Interlok Version (e.g. 3.12.0.3-RELEASE)'
        type: string
        required: true
  push:  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: support/3.12.x
        token: ${{ secrets.INTERLOKDEV_GITHUB_TOKEN }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 1.8
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper

