name: Publish 3.12 Release

on:
  push:
    tags:
      - '3.12.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 1.8
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
    - name: Gradle Build and Publish
      run: |
        echo "::notice ::Release version ${{ github.ref_name }}-RELEASE"
        echo "default.jdbc.storedproc.tests.enabled=false" >> ./interlok-core/build.properties
        echo "junit.jms.tests.enabled=false" >> ./interlok-core/build.properties
        ./gradlew -Djava.security.egd=file:/dev/./urandom -Dorg.gradle.console=plain --no-daemon -PverboseTests=true test publish -PinterlokCoreVersion=${{ github.ref_name }}-RELEASE -PreleaseVersion=${{ github.ref_name }}-RELEASE -PmavenPublishUrl=https://nexus.adaptris.net/nexus/content/repositories/releases
      env:
        ORG_GRADLE_PROJECT_repoUsername: deployment
        ORG_GRADLE_PROJECT_repoPassword: ${{ secrets.NEXUS_REPO_PASSWORD }}
