name: Publish 3.12 Release

on:
  workflow_dispatch:
    inputs:
      interlok-version:
        description: 'Interlok Version (e.g. 3.12.0.3-RELEASE)'
        type: string
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: support/3.12.x
        token: ${{ secrets.INTERLOKDEV_GITHUB_TOKEN }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 1.8
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
    - name: Gradle Build and Publish
      run: |
        echo "default.jdbc.storedproc.tests.enabled=false" >> ./interlok-core/build.properties
        echo "junit.jms.tests.enabled=false" >> ./interlok-core/build.properties
        ./gradlew -Djava.security.egd=file:/dev/./urandom -Dorg.gradle.console=plain --no-daemon -PverboseTests=true test publish -PinterlokCoreVersion=${{ inputs.interlok-version }} -PreleaseVersion=${{ inputs.interlok-version }} -PmavenPublishUrl=https://nexus.adaptris.net/nexus/content/repositories/releases
      env:
        ORG_GRADLE_PROJECT_repoUsername: deployment
        ORG_GRADLE_PROJECT_repoPassword: ${{ secrets.NEXUS_REPO_PASSWORD }}
    - name: Tag
      run: |
        interlokVersion=${{ inputs.interlok-version }}
        # Remove -RELEASE from the version
        tagVersion=${interlokVersion/-RELEASE/""}
        git tag -a $tagVersion -m "Add tag $tagVersion"
        git push origin --tags
